### ISSUE TITLE
Estudo sobre metodologias ágeis

### ISSUE THREAD

**Issue by Potatoyz908** [unb-mds/2024-2-Squad03#1]
### **Desenvolvimento e Difusão da Cultura de Inovação Ágil**
---
#### **O que é?**
Com o objetivo de aumentar a produtividade e acelerar o aprendizado de novas ideias e abordagens, serão discutidas tecnologias como o **Scrum** e o **Kanban**. O foco é criar um ambiente de inovação constante, que beneficie tanto o desempenho do time quanto o desenvolvimento do projeto.

#### **Como funciona?**
Após a leitura do livro de @RochaCarla — *"Como Acelerar o Aprendizado e Disseminar a Cultura de Inovação Ágil"* — o coelho fará um breve resumo dos principais tópicos, destacando práticas que podem melhorar o desempenho do time e promover a disseminação de uma cultura de aprendizado ágil.

#### **Quem serão os Coelhos?**
Os responsáveis por apresentar a discussão serão **Euller Júlio**, @Potatoyz908, e **Ana Elisa**, @anaelisaramos.

#### **Tópicos a serem estudados:**
- [x] **Objetivo das Metodologias Ágeis**
- [x] **Descrição sobre o Scrum**
- [x] **Aplicabilidade em nosso Projeto**
- [x] **Storymap** 

#### **Notion de Estudo:**
[**Clique aqui**](https://www.notion.so/Desenvolvimento-e-Difus-o-da-Cultura-de-Inova-o-gil-12935f46816581c2b548e2013ef03f84?pvs=4) para acessar o Notion com os materiais de estudo e referências.

**Comment by anaelisaramos** [comment]
Estudo finalizado com sucesso ✅🎉

**Comment by 314dro** [comment]
Ótimo trabalho no estudo de vocês! Parabéns :clap::clap:
