### ISSUE TITLE
Pesquisa sobre Arquitetura de Software

### ISSUE THREAD

**Issue by 314dro** [unb-mds/2024-2-Squad03#2]
### **Pesquisa sobre Arquitetura de Software**
---
#### **O que é?**
A arquitetura de software refere-se, de maneira resumida, à abordagem adotada para gerenciar os componentes essenciais de um projeto, definidos e organizados pelos desenvolvedores.

#### **Porquê é importante?**
A arquitetura é fundamental para o desenvolvimento de software, pois, sem ela, o código pode se tornar desorganizado e confuso, o que dificulta e prolonga o processo de implementação das modificações necessárias. Quanto maior a qualidade interna do produto, mais rapidamente serão entregues as funcionalidades, assim, acelerando o desenvolvimento do software.

#### **Quem serão os Coelhos?**
Os responsáveis por apresentar a por esta tarefa serão **Pedro Silva**, @314dro e **Tiago Balieiro**, @TiagoBalieiro.

#### **Tópicos a serem estudados:**
- [x] **Documentação**
- [x] **Staks** 
- [x] **Framework**
- [x] **API**

#### **Notion com os estudos:**
[**Clique aqui**](https://checker-wrist-2f5.notion.site/Arquitetura-de-Software-e3434f0456cf444ab594daecd10cb374) para acessar o Notion com os materiais de estudo e referências.

**Comment by Potatoyz908** [comment]
Vi que vocês finalizaram o estudo, excelente trabalho!

**Comment by TiagoBalieiro** [comment]
Obrigado Euller!

**Comment by Potatoyz908** [comment]
Após conversarmos com a professora Carla, ela sugeriu que organizássemos os arquivos em Markdown do Notion, contendo os estudos sobre coelhos, em uma pasta específica, ao invés de mantê-los somente na issue. O que acham de movermos esses estudos para a pasta dedicada aos coelhos?
