### ISSUE TITLE
Estudo sobre GitHub, GitFlow e DevOps

### ISSUE THREAD

**Issue by pedroeverton217** [unb-mds/2024-2-Squad03#3]
### **GitHub, GitFlow e DevOps**
---
### **O que é?**
Pode-se dizer que GitHub é uma plataforma de hospedagem de código-fonte e controle de versão, utilizando o sistema Git. Enquanto isso, GitFlow é um modelo de ramificação (branching) para Git que define um processo estruturado para o desenvolvimento de software. Além disso, DevOps é uma abordagem e um conjunto de práticas que combinam o desenvolvimento de software ("Dev") e operações de TI ("Ops") para acelerar o ciclo de vida do desenvolvimento de software.

### **Quais são suas importâncias e vantagens?**
A plataforma GitHub permite que desenvolvedores de software colaborem em projetos de forma eficiente, oferecendo ferramentas para versionamento, revisão de código, integração contínua, entre outros, assim como, o GitFlow é amplamente utilizado em equipes de desenvolvimento para organizar e facilitar o fluxo de trabalho em projetos de software.
O objetivo principal do DevOps é promover uma colaboração mais próxima entre desenvolvedores e operadores de TI, automatizando processos e integrando ferramentas que ajudem a melhorar a qualidade, eficiência e velocidade de entrega de software. Além disso, a prática de DevOps ajuda as empresas a responderem rapidamente às necessidades do mercado, a melhorar a qualidade do software e a reduzir o tempo para a entrega de novas funcionalidades.

#### **Quem serão os Coelhos?**
Os responsáveis por apresentar a discussão serão **Pedro Everton**, @pedroeverton217,  **Davi Camilo**, @Davicamilo23 e Leonardo Ramiro **@leoramiroo** .

#### **Link do Notion**
https://tasteful-quark-7f8.notion.site/Estudos-12dd1224ac748046b06de6f987bd0691?pvs=4

#### **Tópicos a serem estudados:**
- [x] **GitHub Actions**
- [x] **GitFlow**
- [x] **Cultura e Colaboração DevOps**
- [x] **Automatização e Ferramentas DevOps**

**Comment by Potatoyz908** [comment]
Olá, equipe! Notei que a descrição desta issue possui algumas inconsistências. Seria interessante revisar os detalhes para garantir maior clareza e precisão nas informações.

**Comment by leoramiroo** [comment]
Estudo finalizado com sucesso!

**Comment by Potatoyz908** [comment]
Excelente trabalho, equipe! Issue concluída com sucesso e objetivos atingidos.

**Comment by Potatoyz908** [comment]
Após conversarmos com a professora Carla, ela sugeriu que comitássemos os arquivos em Markdown do Notion, contendo os estudos sobre coelhos, em uma pasta dedicada, ao invés de deixá-los apenas na issue. O que acham de transferirmos esses estudos para a pasta dos coelhos?

**Comment by leoramiroo** [comment]
Bem observado, já estamos trabalhando nisso!!
