### ISSUE TITLE
Github(Issue): Desenvolver e aplicar template para tasks gerais

### ISSUE THREAD

**Issue by leoramiroo** [unb-mds/2024-2-Squad03#5]
**A sua solicitação de funcionalidade está relacionada a um problema? Por favor, descreva.**
Não. A funcionalidade solicitada é a criação de issue templates para definição de tasks em geral do projeto, a qual não estejam relacionadas com novas features, bugs, documentações ou estudos.

**Descreva a solução desejada**
Criação dos arquivos:
- [x] task.md

- [x] rabbit.md

- [x] feature-request.mds

- [x] docs-repair.md

- [x] bug-report.md

- [x] Criação de labels para cada situação requisitada no projeto

**Contexto adicional**
O template será útil para organizar as tasks gerais de cada setor de produção do projeto.

**Comment by leoramiroo** [comment]
Tarefa finalizada com sucesso!

**Comment by Potatoyz908** [comment]
bom trabalho! Tarefa concluída com êxito!
